name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-18"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "learn_hono"
database_id = "00f3cf5e-d20e-4af0-b544-a51192193b7c"
migrations_dir = "./src/db/migrations"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1